- name: set vlans
  ios_command:
    commands:
      - conf t
      - vlan {{ item.key }}
      - name {{ item.value.name }}
    provider: "{{ cli }}"
  with_dict: "{{ vlans }}"

- name: assign interfaces to vlans
  ios_command:
    commands:
      - conf t
      - int range fa0/{{ item.key }}
      - switchport access vlan {{ item.value.vlan }}
    provider: "{{ cli }}"
  with_dict: "{{ interfaces }}"

- name: set spanning-tree
  ios_command:
    commands:
      - conf t
      - spanning-tree vlan 99 priority 4096
    provider: "{{ cli }}"
