# /ios.yaml
---
- hosts: server-switches
  gather_facts: no
  connection: local

  vars:
    limit_to: "*"

  roles:
    - common-command
#   - common-config
    - vtp
    - trunking
    - vlan
    - saveconfig

#- hosts: client-switches
#  gather_facts: no
#  connection: local
#
#  vars:
#    limit_to: "*"
#
#  roles:
#    - common-command
##  - common-config
#    - vtp
#    - trunking
#    - saveconfig
