# roles/common-config/tasks/main.yaml

- name: set hostname
  ios_config:
    lines:
      - ['hostname {{inventory_hostname}}']
    provider: "{{ cli }}"

- name: disable service 'config'
  ios_config:
    lines:
      - ['no service config']
    provider: "{{ cli }}"
